# Generated by Django 3.1.3 on 2021-01-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeBuildSite', '0005_listarticle_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AlterModelOptions(
            name='listarticle',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'картинка', 'verbose_name_plural': 'картинки'},
        ),
        migrations.AlterModelOptions(
            name='servicearticle',
            options={'verbose_name': 'услуга', 'verbose_name_plural': 'услуги'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='listarticle',
            name='image',
            field=models.ImageField(blank=True, upload_to='listArticles', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='listarticle',
            name='text',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, upload_to='main', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.TextField(blank=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='servicearticle',
            name='text',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
    ]
